GetTemplateByShortURL
dudasaus/tierlist pull request #31
Opened 2024-04-27 21:46 UTC by dudasaus

2024-04-27 22:05 UTC, dudasaus commented
@white0ut is there codegen for server/get_template_s.go ? Or are those all manually built?

2024-04-28 01:13 UTC, white0ut commented on backend/backend-api.yaml
> +  /templates/s/{shortUrl}:
I'm kind of disappointed there's no [AIP](https://google.aip.dev/) for this unless I'm missing something.

The closest I can think of is to do a [Custom Method](https://google.aip.dev/136) which may be `/templates/:getByShortUrl`

We could also do a query filter on the List call to `/templates`.

I was trying to follow the AIP, but maybe that's tailored more for protobufs. If we depart from it it's nbd.

2024-04-28 01:15 UTC, white0ut commented on backend/resources/resources_test.go
> +	t.Run("GetTemplateByShortURL returns found template", func(t *testing.T) {
haha I've never seen tests implemented this way, normally they're separate tests, the function only needs to have a "Test" prefix and it will get picked up.

2024-04-28 01:19 UTC, white0ut requested changes

2024-04-28 01:19 UTC, white0ut commented on backend/backend-api.yaml
> +  /templates/s/{shortUrl}:
I'm kind of disappointed there's no [AIP](https://google.aip.dev/) for this unless I'm missing something.

The closest I can think of is to do a [Custom Method](https://google.aip.dev/136) which may be /templates/:getByShortUrl

We could also do a query filter on the List call to /templates.

I was trying to follow the AIP, but maybe that's tailored more for protobufs. If we depart from it it's nbd.

2024-04-28 01:19 UTC, white0ut commented on backend/resources/resources_test.go
> +	t.Run("GetTemplateByShortURL returns found template", func(t *testing.T) {
I've never seen tests implemented this way, normally they're separate tests, the function only needs to have a "Test" prefix and it will get picked up.

2024-04-28 01:42 UTC, white0ut commented on backend/backend-api.yaml
> +  /templates/s/{shortUrl}:
I went with `templates/shortUrl/{shortUrl}`

2024-04-28 01:44 UTC, merged